//
//  Playlist_ManagerTests.m
//  Playlist ManagerTests
//
//  Created by Mark Landgrebe on 11/2/14.
//
//

#import <UIKit/UIKit.h>
#import <XCTest/XCTest.h>


/*
 
 This file was automatically generated by Xcode. All unit tests are included in separate test files specific to each class
 
 */


@interface Playlist_ManagerTests : XCTestCase

@end

@implementation Playlist_ManagerTests

- (void)setUp {
    [super setUp];
    // Put setup code here. This method is called before the invocation of each test method in the class.
}

- (void)tearDown {
    // Put teardown code here. This method is called after the invocation of each test method in the class.
    [super tearDown];
}

- (void)testExample {
    // This is an example of a functional test case.
    XCTAssert(YES, @"Pass");
}

- (void)testPerformanceExample {
    // This is an example of a performance test case.
    [self measureBlock:^{
        // Put the code you want to measure the time of here.
    }];
}

@end
